name: crypto-forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - requests
  - pip
  - pip:
    - ta
    - lightgbm