data: 
  raw_path: "data/raw/top_100_cryptos_with_correct_network.csv"
  processed_dir: "data/processed/"
  external_dir: "data/external/"


model:
  model_dir: "models/"
  supported_symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "BNBUSDT", "XRPUSDT", "DOTUSDT", "DOGEUSDT", "SOLUSDT"]

api:
  host:  "0.0.0.0"
  port: 5001
  debug: False

features:
  lags: [1, 2, 3, 5, 7, 14, 30]
  windows: [7, 14, 30, 60]

binance:
  base_url: "https://api3.binance.com"
  intervals: ["1d", "4h", "1h"]
